// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0gx2qso6oE5iBW7V1mOoFbAzRAjQXrU',
    appId: '1:329083865994:web:69a9192a7b0ae313095673',
    messagingSenderId: '329083865994',
    projectId: 'wiz-flutter-project',
    authDomain: 'wiz-flutter-project.firebaseapp.com',
    storageBucket: 'wiz-flutter-project.appspot.com',
    measurementId: 'G-C8Q804DVJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWwYXFd03T5emdkFxDeq-P8caW2ee84E',
    appId: '1:329083865994:android:20c81901d6d541eb095673',
    messagingSenderId: '329083865994',
    projectId: 'wiz-flutter-project',
    storageBucket: 'wiz-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbaNSOSMG0zYLVUCEFhbPM0DeDGE8f8Pk',
    appId: '1:329083865994:ios:266d7619efc0a91e095673',
    messagingSenderId: '329083865994',
    projectId: 'wiz-flutter-project',
    storageBucket: 'wiz-flutter-project.appspot.com',
    iosBundleId: 'com.example.wiz',
  );
}
